# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://gamba-dev.github.io/gamba/"

git_url = "https://github.com/gamba-dev/gamba/tree/main/"

def custom_doc_links(name): return None
