# AUTOGENERATED! DO NOT EDIT! File to edit: 20_data.ipynb (unless otherwise specified).

__all__ = ['read_csv', 'check_data']

# Cell
def read_csv(file, parse_dates=[], index_col=None, delimiter=",", dummy_data=False):

    df = pd.read_csv(
        file, parse_dates=parse_dates, index_col=index_col, delimiter=delimiter
    )

    return df

# Cell
def check_data(dataframe):

    column_names = dataframe.columns

    print(column_names)